resolver: lts-12.22

packages:
- '.'

extra-deps:
- scotty-0.11.3
- scotty-tls-0.4.1
- blaze-html-0.9.1.1
- blaze-markup-0.8.2.2
- text-1.2.3.1
- mtl-2.2.2
- transformers-0.5.5.0
- bytestring-0.10.8.2
- bifunctors-5.5.3
- cmark-gfm-0.1.6
- directory-1.3.3.0
- filepath-1.4.2.1
- mime-types-0.1.0.9
- containers-0.5.11.0
- rss-3000.2.0.7
- HaXml-1.25.5
- polyparse-1.12.1
- time-1.8.0.2
- network-uri-2.6.1.0

flags: {}

extra-package-dbs: []

# Control whether we use the GHC we find on the path
# system-ghc: true

# Allow a newer minor version of GHC than the snapshot specifies
compiler-check: newer-minor
